name: build
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  # Windows 打包：隐藏CMD黑窗 + fyne打包内置EXE图标
  build-windows:
    runs-on: windows-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置Go环境
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: 设置国内Go代理
        run: go env -w GOPROXY=https://goproxy.cn,direct

      - name: 安装Fyne打包工具
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Windows打包（隐藏控制台+绑定图标+发布精简版）
        run: fyne package -os windows -icon icon.png -release

      - name: 上传Windows打包产物
        uses: actions/upload-artifact@v4
        with:
          name: smartedu-dl-Windows
          path: smartedu-dl.exe

  # Linux 打包
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置Go环境
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: 安装Fyne系统依赖
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev xorg-dev

      - name: 设置国内Go代理
        run: go env -w GOPROXY=https://goproxy.cn,direct

      - name: Linux打包
        run: fyne package -os linux -icon app_icon.png -release

      - name: 上传Linux打包产物
        uses: actions/upload-artifact@v4
        with:
          name: smartedu-dl-Linux
          path: smartedu-dl

  # MacOS 打包
  build-macos:
    runs-on: macos-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置Go环境
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: 设置国内Go代理
        run: go env -w GOPROXY=https://goproxy.cn,direct

      - name: Mac打包
        run: fyne package -os darwin -icon app_icon.png -release

      - name: 上传Mac打包产物
        uses: actions/upload-artifact@v4
        with:
          name: smartedu-dl-macOS
          path: smartedu-dl.app
