name: Build
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: 配置Go代理
        run: go env -w GOPROXY=https://goproxy.cn,direct
      - name: 编译Windows可执行程序（隐藏CMD黑窗）
        run: go build -ldflags="-s -w -H windowsgui" -o smartedu-dl.exe
      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: smartedu-dl-windows
          path: smartedu-dl.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: 安装Fyne依赖库
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev xorg-dev
      - name: 配置Go代理
        run: go env -w GOPROXY=https://goproxy.cn,direct
      - name: 编译Linux程序
        run: go build -o smartedu-dl-linux
      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: smartedu-dl-linux
          path: smartedu-dl-linux

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: 配置Go代理
        run: go env -w GOPROXY=https://goproxy.cn,direct
      - name: 编译Mac程序
        run: go build -o smartedu-dl-macos
      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: smartedu-dl-macos
          path: smartedu-dl-macos
